### ISSUE TITLE
Find or Create Meetup Widget for Homepage

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/opensandiego.github.io#10]
The move to github pages has limited our ability to integrate with Meetup. Ideally we want to be able to have a feed on the home page showing the next upcoming event. This would probably best be pulled in via Javascript.

The best would be an iframe widget, but I have not yet found one.

For a JS embed, there is some documentation available.  A good starting point would be:
https://www.meetup.com/meetup_api/foundry/

API keys may be required for the JS powered embed, and this is not ideal to have checked-in to a git repo. 

The final alternative is to setup a secondary app on Heroku (or even an AWS lambda task) which dynamically assembles the meetup feed and serves it or posts it to S3 or otherwise.

The meetup widget should be showing meetup events from:
https://www.meetup.com/Open-San-Diego/

**Comment by carloslazo** [comment]
@nikolajbaer 

The Iframe widget that is provided in the link you posted https://www.meetup.com/meetup_api/foundry/ seems like a good solution since it just requires a URL name and shows the next upcoming event.

Are there other features that you were thinking of? 

Here is the picture of the widget.

<img width="228" alt="screen shot 2019-02-23 at 9 03 25 pm" src="https://user-images.githubusercontent.com/21298082/53295387-1608f100-37af-11e9-8071-a69241371e0d.png">

**Comment by nikolajbaer** [comment]
Closing this for now. It could use some style tweaks but I think the core issue here is resolved.
