### ISSUE TITLE
Setup Jekyll SCSS build, and JS Build

### ISSUE THREAD

**Issue by nikolajbaer** [opensandiego/opensandiego.github.io#9]
With the updated Jekyll theme, it will be good to cleanup the build process.

Ideally if Github would do a build upon commit, we could just have the raw SCSS and the rest would be built. However, I am not sure if that works if we are just doing stock bootstrap (not a prebuilt github theme).

More reading on that:
https://help.github.com/en/articles/about-jekyll-themes-on-github

Alternatively, we can continue with what is there right now, a package.json file that we can run `npm run build` and then commit the main.css  file.

This second option might be the best as we will probably want to add a JS file to the mix that is built with the same process (at the least to manage bootstrap JS add-ons).

**Comment by jhuynh85** [comment]
@nikolajbaer I looked into this and it seems that Github Pages can automatically compile `.scss` files if you add two lines of triple dashes (`---`) at the beginning of the file (https://jekyllrb.com/docs/assets/). 

The problem is our `main.scss` relies on the Bootstrap npm package, but since Github Pages doesn't support npm, it has no way of getting the package.

We _could_  copy the whole `bootstrap` folder from `node_modules` and commit it, but that doesn't seem like an ideal solution.

**Comment by nikolajbaer** [comment]
@jhuynh85 Thanks for checking into this! 

I think you are right, that it is probably best to keep as is. It isn't too hard to run _npm run build_ and recommit the main.css file, although it is an extra step.

As to Javascript, right now we are pretty much just doing some <script> tags and includes for embeds.  It might be worth considering adding a JS build step as well for the bootstrap includes, but also probably not necessary as we can link that from standard CDN hosting.
